#ifndef __COCOA_VULKAN_CONFIG_H__
#define __COCOA_VULKAN_CONFIG_H__

#include <vulkan/vulkan.h>
#define CIALLO_VKAPI_VERSION        VK_API_VERSION_1_1
#define CIALLO_ENGINE_MAJOR         1
#define CIALLO_ENGINE_MINOR         0
#define CIALLO_ENGINE_PATCH         0

#define CIALLO_ENGINE_NAME          "Cocoa/Ciallo"
#define CIALLO_ENGINE_VERSION       VK_MAKE_VERSION(CIALLO_ENGINE_MAJOR, CIALLO_ENGINE_MINOR, CIALLO_ENGINE_PATCH)

#endif // #ifndef __COCOA_VULKAN_CONFIG_H__
